/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiGoogleSearchServerRouteImport } from './routes/api/googleSearch'
import { ServerRoute as ApiFoursquareSearchServerRouteImport } from './routes/api/foursquareSearch'
import { ServerRoute as ApiDebugServerRouteImport } from './routes/api/debug'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleSearchServerRoute = ApiGoogleSearchServerRouteImport.update({
  id: '/api/googleSearch',
  path: '/api/googleSearch',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiFoursquareSearchServerRoute =
  ApiFoursquareSearchServerRouteImport.update({
    id: '/api/foursquareSearch',
    path: '/api/foursquareSearch',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiDebugServerRoute = ApiDebugServerRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/debug': typeof ApiDebugServerRoute
  '/api/foursquareSearch': typeof ApiFoursquareSearchServerRoute
  '/api/googleSearch': typeof ApiGoogleSearchServerRoute
}
export interface FileServerRoutesByTo {
  '/api/debug': typeof ApiDebugServerRoute
  '/api/foursquareSearch': typeof ApiFoursquareSearchServerRoute
  '/api/googleSearch': typeof ApiGoogleSearchServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/debug': typeof ApiDebugServerRoute
  '/api/foursquareSearch': typeof ApiFoursquareSearchServerRoute
  '/api/googleSearch': typeof ApiGoogleSearchServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/debug' | '/api/foursquareSearch' | '/api/googleSearch'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/debug' | '/api/foursquareSearch' | '/api/googleSearch'
  id: '__root__' | '/api/debug' | '/api/foursquareSearch' | '/api/googleSearch'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiDebugServerRoute: typeof ApiDebugServerRoute
  ApiFoursquareSearchServerRoute: typeof ApiFoursquareSearchServerRoute
  ApiGoogleSearchServerRoute: typeof ApiGoogleSearchServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/googleSearch': {
      id: '/api/googleSearch'
      path: '/api/googleSearch'
      fullPath: '/api/googleSearch'
      preLoaderRoute: typeof ApiGoogleSearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/foursquareSearch': {
      id: '/api/foursquareSearch'
      path: '/api/foursquareSearch'
      fullPath: '/api/foursquareSearch'
      preLoaderRoute: typeof ApiFoursquareSearchServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiDebugServerRoute: ApiDebugServerRoute,
  ApiFoursquareSearchServerRoute: ApiFoursquareSearchServerRoute,
  ApiGoogleSearchServerRoute: ApiGoogleSearchServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
